### ISSUE TITLE
"Backup Error"

### ISSUE THREAD

**Issue by beschoenen** [robweber/xbmcbackup#121]
I get this message when starting KODI

"Backup Error, please check the logs"

```
Kodi (18.0-ALPHA1 Git:20171202-bad23d6). Platform: Android ARM 64-bit
```

```
20:20:22.737 T:139065685072   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named apiclient.discovery
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/scheduler.py", line 9, in <module>
                                                from resources.lib.backup import XbmcBackup
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/resources/lib/backup.py", line 7, in <module>
                                                from vfs import XBMCFileSystem,DropboxFileSystem,ZipFileSystem,GoogleDriveFilesystem
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/resources/lib/vfs.py", line 9, in <module>
                                                from pydrive.auth import GoogleAuth
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/resources/lib/pydrive/auth.py", line 6, in <module>
                                                from apiclient.discovery import build
                                            ImportError: No module named apiclient.discovery
                                            -->End of Python script error report<--
```

**Comment by oomasoo** [comment]
Getting the same, first a few days ago on a kodi 18 machine and now today on a 17.6 setup

**Comment by robweber** [comment]
Same as #120 so closing this just to keep things in one place.
