### ISSUE TITLE
Scheduler Error If No last_run.txt file

### ISSUE THREAD

**Issue by robweber** [robweber/xbmcbackup#124]
From @tknorris

There's also a bug in this build in scheduler.py where if next_run.txt doesn't exist and the scheduler is turned on then nr doesn't get initialized so you get a UnboundLocalError.

```
                                        Error Type: <type 'exceptions.UnboundLocalError'>
                                        Error Contents: local variable 'nr' referenced before assignment
                                        Traceback (most recent call last):
                                          File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/scheduler.py", line 189, in <module>
                                            BackupScheduler().start()
                                          File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/scheduler.py", line 38, in __init__
                                            if(0 < nr <= time.time() and utils.getSetting('schedule_miss') == 'true'):
                                        UnboundLocalError: local variable 'nr' referenced before assignment
                                        -->End of Python script error report<--
```
This fix, of course, is to set nr to 0 earlier in the method so this case is covered.

**Comment by robweber** [comment]
Also added this to repo pull request so when it's eventually merged it will be included.
