### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by elreymon** [robweber/xbmcbackup#137]
I´m affraid the character 'ñ' in **guisettings.xml** is causing problems while decoding
`<country>España (24 horas)</country>`

As you can see:

```
20:46:13.823 T:1458828032  NOTICE: script.xbmcbackup-1.1.2: updating: locale.country, value: EspaÃ±a (24 horas)
20:46:13.838 T:1458828032   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.UnicodeDecodeError'>
Error Contents: 'ascii' codec can't decode byte 0xc3 in position 4: ordinal not in range(128)
Traceback (most recent call last):
File "/home/osmc/.kodi/addons/script.xbmcbackup/default.py", line 73, in <module>
backup.run(mode)
File "/home/osmc/.kodi/addons/script.xbmcbackup/resources/lib/backup.py", line 452, in run
gui_settings.run()
File "/home/osmc/.kodi/addons/script.xbmcbackup/resources/lib/guisettings.py", line 47, in run
xbmc.executeJSONRPC('{"jsonrpc":"2.0", "id":1, "method":"Settings.SetSettingValue","params":{"setting":"' + aSetting.json_name() + '","value":"' + utils.encode(aSetting.value) + '"}}')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4: ordinal not in range(128)
-->End of Python script error report<--
```

**Comment by robweber** [comment]
Closing since this shouldn't be so much of a problem with Python3 support in Kodi now.
