### ISSUE TITLE
Backup error

### ISSUE THREAD

**Issue by mcsdodo** [robweber/xbmcbackup#139]
21:14:28.099 T:3145917184   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: Unknown exception thrown from the call "read"
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/script.xbmcbackup/default.py", line 73, in <module>
                                                backup.run(mode)
                                              File "/home/osmc/.kodi/addons/script.xbmcbackup/resources/lib/backup.py", line 257, in run
                                                filesCopied = self.backupFiles(fileGroup['files'],self.xbmc_vfs,self.remote_vfs)
                                              File "/home/osmc/.kodi/addons/script.xbmcbackup/resources/lib/backup.py", line 483, in backupFiles
                                                wroteFile = dest.put(aFile,dest.root_path + aFile[len(source.root_path):])
                                              File "/home/osmc/.kodi/addons/script.xbmcbackup/resources/lib/vfs.py", line 100, in put
                                                self.zip.writestr(utils.encode(dest),aFile.read())
                                            RuntimeError: Unknown exception thrown from the call "read"

**Comment by mcsdodo** [comment]
running version 1.1.2

**Comment by mcsdodo** [comment]
The cause of this issue was insufficient storage space on my device. Script didn't have enough space to create backup file.
A thought for improvement - a proper error message when there is not enough space on the device would be nice.
