### ISSUE TITLE
Cannot recover backup

### ISSUE THREAD

**Issue by stdedos** [robweber/xbmcbackup#181]
Is any of these https://github.com/robweber/xbmcbackup/issues/158, https://github.com/robweber/xbmcbackup/issues/145 that?

**Describe the problem**

**Platform and Kodi version**
What OS and Kodi version are you using? (Rpi, Android, etc)

**Link to Debug Log**
```
2021-02-07 23:45:15.991 T:7701  NOTICE: -----------------------------------------------------------------------
2021-02-07 23:45:15.991 T:7701  NOTICE: Starting Kodi (18.9 (18.9.0) Git:20201023-0655c2c718). Platform: Android ARM 32-bit
2021-02-08 00:39:50.915 T:9258   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'zipfile.BadZipfile'>
                                            Error Contents: File is not a zip file
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/default.py", line 73, in <module>
                                                backup.run(mode)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/resources/lib/backup.py", line 312, in run
                                                zip_vfs = ZipFileSystem(xbmc.translatePath("special://temp/"+ self.restore_point),'r')
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/resources/lib/vfs.py", line 88, in __init__
                                                self.zip = zipfile.ZipFile(rootString,mode=mode,compression=zipfile.ZIP_DEFLATED,allowZip64=True)
                                              File "/home/jenkins/workspace/Android-ARM-Leia/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/zipfile.py", line 770, in __init__
                                              File "/home/jenkins/workspace/Android-ARM-Leia/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/zipfile.py", line 811, in _RealGetContents
                                            BadZipfile: File is not a zip file
                                            -->End of Python script error report<--
2021-02-08 00:41:28.338 T:7701  NOTICE: NFS is idle. Closing the remaining connections.
2021-02-08 00:41:53.778 T:9292  NOTICE: script.xbmcbackup-1.1.3: Starting
2021-02-08 00:41:59.416 T:9292  NOTICE: script.xbmcbackup-1.1.3: Local Dir: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/
2021-02-08 00:41:59.416 T:9292  NOTICE: script.xbmcbackup-1.1.3: Remote Dir: nfs://1.1.1.1/KodiStorage/backups/
2021-02-08 00:41:59.417 T:9292  NOTICE: script.xbmcbackup-1.1.3: Mode - Restore
2021-02-08 00:41:59.417 T:9292  NOTICE: script.xbmcbackup-1.1.3: copying zip file: 202102050057.zip
2021-02-08 00:41:59.418 T:9292  NOTICE: script.xbmcbackup-1.1.3: Writing files to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp/
2021-02-08 00:41:59.418 T:9292  NOTICE: script.xbmcbackup-1.1.3: Source: nfs://1.1.1.1/KodiStorage/backups/
2021-02-08 00:42:05.345 T:9292   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'zipfile.BadZipfile'>
                                            Error Contents: File is not a zip file
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/default.py", line 73, in <module>
                                                backup.run(mode)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/resources/lib/backup.py", line 312, in run
                                                zip_vfs = ZipFileSystem(xbmc.translatePath("special://temp/"+ self.restore_point),'r')
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/resources/lib/vfs.py", line 88, in __init__
                                                self.zip = zipfile.ZipFile(rootString,mode=mode,compression=zipfile.ZIP_DEFLATED,allowZip64=True)
                                              File "/home/jenkins/workspace/Android-ARM-Leia/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/zipfile.py", line 770, in __init__
                                              File "/home/jenkins/workspace/Android-ARM-Leia/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/zipfile.py", line 811, in _RealGetContents
                                            BadZipfile: File is not a zip file
                                            -->End of Python script error report<--
2021-02-08 00:42:14.068 T:9299  NOTICE: script.xbmcbackup-1.1.3: Starting
2021-02-08 00:42:16.314 T:9299  NOTICE: script.xbmcbackup-1.1.3: Local Dir: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/
2021-02-08 00:42:16.314 T:9299  NOTICE: script.xbmcbackup-1.1.3: Remote Dir: nfs://1.1.1.1/KodiStorage/backups/
2021-02-08 00:42:16.316 T:9299  NOTICE: script.xbmcbackup-1.1.3: Mode - Restore
2021-02-08 00:42:16.316 T:9299  NOTICE: script.xbmcbackup-1.1.3: copying zip file: 202102050054.zip
2021-02-08 00:42:16.318 T:9299  NOTICE: script.xbmcbackup-1.1.3: Writing files to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp/
2021-02-08 00:42:16.318 T:9299  NOTICE: script.xbmcbackup-1.1.3: Source: nfs://1.1.1.1/KodiStorage/backups/
2021-02-08 00:42:23.514 T:9299   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'zipfile.BadZipfile'>
                                            Error Contents: File is not a zip file
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/default.py", line 73, in <module>
                                                backup.run(mode)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/resources/lib/backup.py", line 312, in run
                                                zip_vfs = ZipFileSystem(xbmc.translatePath("special://temp/"+ self.restore_point),'r')
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/resources/lib/vfs.py", line 88, in __init__
                                                self.zip = zipfile.ZipFile(rootString,mode=mode,compression=zipfile.ZIP_DEFLATED,allowZip64=True)
                                              File "/home/jenkins/workspace/Android-ARM-Leia/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/zipfile.py", line 770, in __init__
                                              File "/home/jenkins/workspace/Android-ARM-Leia/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/zipfile.py", line 811, in _RealGetContents
                                            BadZipfile: File is not a zip file
                                            -->End of Python script error report<--
2021-02-08 00:42:31.569 T:9304  NOTICE: script.xbmcbackup-1.1.3: Starting
2021-02-08 00:42:33.967 T:9304  NOTICE: script.xbmcbackup-1.1.3: Local Dir: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/
2021-02-08 00:42:33.967 T:9304  NOTICE: script.xbmcbackup-1.1.3: Remote Dir: nfs://1.1.1.1/KodiStorage/backups/
2021-02-08 00:42:33.969 T:9304  NOTICE: script.xbmcbackup-1.1.3: Mode - Restore
2021-02-08 00:42:33.969 T:9304  NOTICE: script.xbmcbackup-1.1.3: copying zip file: 202102040020.zip
2021-02-08 00:42:33.970 T:9304  NOTICE: script.xbmcbackup-1.1.3: Writing files to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp/
2021-02-08 00:42:33.970 T:9304  NOTICE: script.xbmcbackup-1.1.3: Source: nfs://1.1.1.1/KodiStorage/backups/
2021-02-08 00:42:40.056 T:9304   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'zipfile.BadZipfile'>
                                            Error Contents: File is not a zip file
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/default.py", line 73, in <module>
                                                backup.run(mode)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/resources/lib/backup.py", line 312, in run
                                                zip_vfs = ZipFileSystem(xbmc.translatePath("special://temp/"+ self.restore_point),'r')
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/resources/lib/vfs.py", line 88, in __init__
                                                self.zip = zipfile.ZipFile(rootString,mode=mode,compression=zipfile.ZIP_DEFLATED,allowZip64=True)
                                              File "/home/jenkins/workspace/Android-ARM-Leia/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/zipfile.py", line 770, in __init__
                                              File "/home/jenkins/workspace/Android-ARM-Leia/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/zipfile.py", line 811, in _RealGetContents
                                            BadZipfile: File is not a zip file
                                            -->End of Python script error report<--
2021-02-08 00:42:50.936 T:9309  NOTICE: script.xbmcbackup-1.1.3: Starting
2021-02-08 00:42:52.486 T:9309  NOTICE: script.xbmcbackup-1.1.3: Local Dir: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/
2021-02-08 00:42:52.487 T:9309  NOTICE: script.xbmcbackup-1.1.3: Remote Dir: nfs://1.1.1.1/KodiStorage/backups/
2021-02-08 00:42:52.488 T:9309  NOTICE: script.xbmcbackup-1.1.3: Mode - Restore
2021-02-08 00:42:52.488 T:9309  NOTICE: script.xbmcbackup-1.1.3: copying zip file: 202102030000.zip
2021-02-08 00:42:52.489 T:9309  NOTICE: script.xbmcbackup-1.1.3: Writing files to: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp/
2021-02-08 00:42:52.490 T:9309  NOTICE: script.xbmcbackup-1.1.3: Source: nfs://1.1.1.1/KodiStorage/backups/
2021-02-08 00:43:00.760 T:9309   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'zipfile.BadZipfile'>
                                            Error Contents: File is not a zip file
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/default.py", line 73, in <module>
                                                backup.run(mode)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/resources/lib/backup.py", line 312, in run
                                                zip_vfs = ZipFileSystem(xbmc.translatePath("special://temp/"+ self.restore_point),'r')
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/resources/lib/vfs.py", line 88, in __init__
                                                self.zip = zipfile.ZipFile(rootString,mode=mode,compression=zipfile.ZIP_DEFLATED,allowZip64=True)
                                              File "/home/jenkins/workspace/Android-ARM-Leia/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/zipfile.py", line 770, in __init__
                                              File "/home/jenkins/workspace/Android-ARM-Leia/tools/depends/xbmc-depends/arm-linux-androideabi-21-release/lib/python2.7/zipfile.py", line 811, in _RealGetContents
                                            BadZipfile: File is not a zip file
                                            -->End of Python script error report<--
2021-02-08 00:44:17.084 T:7713  NOTICE: Trying to open: samplerate: 44100, channelMask: 12, encoding: 4
2021-02-08 00:44:17.090 T:7713  NOTICE: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 44100 format: AE_FMT_FLOAT (AE) method: PCM stream-type: PCM-STREAM min_buffer_size: 30208 m_frames: 1888 m_frameSize: 8 channels: 2
2021-02-08 00:44:28.729 T:7701   ERROR: Control 18 in window 10129 has been asked to focus, but it can't
2021-02-08 00:44:34.013 T:7701   ERROR: Unable to lookup host: ''
2021-02-08 00:45:16.994 T:9351 WARNING: FileNFS::OpenForWrite() called with overwriting enabled! - //KodiStorage/kodi.log
```

**Comment by robweber** [comment]
Yes, it's the same issue. Android systems seem to have this problem occasionally, at least on Python 2. There is a custom branch with a modified zipfile.py file that attempts to fix it. I did not write that file, and am unsure of how it differs from the one bundled with Python. I've been told it works though. I've hesitated putting this into version in the Kodi repo for 2 reasons. 1) I don't like the idea of patching core Python code with replacement files. As Python versions change it will open the door for unneeded maintenance and security issues. 2) I'm hoping this goes away with Python 3. 

If you want to try the [custom branch](https://github.com/robweber/xbmcbackup/tree/krypton_custom_zipfile) as a temporary work around feel free to do so. The other option would be to just not compress your backups.

**Comment by stdedos** [comment]
I've tried replacing the file manually; no luck.

I just went on the file-system and played manually.
Too bad there is no way to save the installed add-ons, except bulk-backup of everything ...

**Comment by robweber** [comment]
If you're doing it manually you have to update the file and also change one line in vfs.py per [this commit](https://github.com/robweber/xbmcbackup/commit/1fb013f33577dc72026434a295e19296830b093f). Unless you're just dropping it right over the original python library zipfile.py file, then I guess you wouldn't. 

You could unzip the file using some other method (on a desktop PC or using CLI) and then point to it as an unzipped backup. That would as well.

**Comment by stdedos** [comment]
> If you're doing it manually you have to update the file and also change one line in vfs.py per [this commit](https://github.com/robweber/xbmcbackup/commit/1fb013f33577dc72026434a295e19296830b093f). Unless you're just dropping it right over the original python library zipfile.py file, then I guess you wouldn't.

Oh. I know what I did wrong now 😂

> You could unzip the file using some other method (on a desktop PC or using CLI) and then point to it as an unzipped backup. That would as well.

Sweet. If Kodi would move forward with v19, so that plugins could move forward with updates too .... 😞
