### ISSUE TITLE
Advanced Editor stacktrace

### ISSUE THREAD

**Issue by stdedos** [robweber/xbmcbackup#183]
**Platform and Kodi version**
Android / v19.0 Matrix

**Describe the problem**
Opening the advanced editor, leads to ....

**Link to Debug Log**
```py
2021-02-21 18:23:49.526 T:5668    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: function missing required argument 'message' (pos 2)
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/launcher.py", line 55, in <module>
                                                       editor.showMainScreen()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/resources/lib/advanced_editor.py", line 198, in showMainScreen
                                                       newSet = self.createSet()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/resources/lib/advanced_editor.py", line 97, in createSet
                                                       enterHome = self.dialog.yesno(utils.getString(30111), line1=utils.getString(30112) + " - " + utils.getString(30114), line2=utils.getString(30113) + " - " + utils.getString(30115), nolabel=utils.getString(30112), yeslabel=utils.getString(30113))
                                                   TypeError: function missing required argument 'message' (pos 2)
                                                   -->End of Python script error report<--
```

**Comment by robweber** [comment]
Thanks for this, thought I hunted down all the ```Dialog()``` library arg changes.
