### ISSUE TITLE
Error 'ModuleNotFoundError'

### ISSUE THREAD

**Issue by Cris--** [robweber/xbmcbackup#204]
Hi, get an error and backup aborts:

`EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'ModuleNotFoundError'>
Error Contents: No module named 'pyqrcode'
Traceback (most recent call last):

File "/storage/.kodi/addons/script.xbmcbackup/service.py", line 1, in <module> from resources.lib.scheduler import BackupScheduler

File "/storage/.kodi/addons/script.xbmcbackup/resources/lib/scheduler.py", line 8, in <module> from resources.lib.backup import XbmcBackup

File "/storage/.kodi/addons/script.xbmcbackup/resources/lib/backup.py", line 10, in <module> from . vfs import XBMCFileSystem, DropboxFileSystem, ZipFileSystem

File "/storage/.kodi/addons/script.xbmcbackup/resources/lib/vfs.py", line 10, in <module> from . authorizers import DropboxAuthorizer

File "/storage/.kodi/addons/script.xbmcbackup/resources/lib/authorizers.py", line 3, in <module> import pyqrcode
ModuleNotFoundError: No module named 'pyqrcode'

-->End of Python script error report<--`

RPi4 / LibreElec 10

**Comment by robweber** [comment]
I've seen this error happen before but not sure what causes it. It's like the dependency isn't being installed correctly even though it's part of the `addon.xml` file. Have you tried uninstalling the addon and then re-installing it? That might kick Kodi into downloading the dependency.
