### ISSUE TITLE
float division by zero when attempting to write file with "Compress Archives"

### ISSUE THREAD

**Issue by sdaau** [robweber/xbmcbackup#209]
**Describe the problem**

Difficult to provide a concise description, but:

With Kodi 19.1 on Android, I try to install via the built-in Kodi repository, as described in: https://kodi.wiki/view/Add-on:Backup

That fails with:

```
2022-02-02 21:24:18.970 T:1695    ERROR <general>: Unable to lookup host: 'mirror.ehv.weppel.nl'
2022-02-02 21:24:18.975 T:1695    ERROR <general>: CCurlFile::Stat - Failed: Couldn't resolve host name(6) for https://mirror.ehv.weppel.nl/kodi/addons/matrix/script.xbmcbackup/script.xbmcbackup-1.6.7.zip
2022-02-02 21:24:18.995 T:1695    ERROR <general>: Unable to lookup host: 'mirror.ehv.weppel.nl'
2022-02-02 21:24:19.000 T:1695    ERROR <general>: CCurlFile::FillBuffer - Failed: Couldn't resolve host name(6)
2022-02-02 21:24:19.000 T:1695    ERROR <general>: CCurlFile::Open failed with code 0 for https://mirror.ehv.weppel.nl/kodi/addons/matrix/script.xbmcbackup/script.xbmcbackup-1.6.7.zip:
                                                   
2022-02-02 21:24:19.002 T:1695    ERROR <general>: CAddonInstallJob[script.xbmcbackup]: failed to download special://home/addons/packages/script.xbmcbackup-1.6.7.zip
2022-02-02 21:24:27.233 T:31658    INFO <general>: WebSocket: connection closed by client
2022-02-02 21:24:27.233 T:31658    INFO <general>: JSONRPC Server: Disconnection detected
2022-02-02 21:24:34.800 T:1801     INFO <general>: [script.logviewer] "GET / HTTP/1.1" 200 -
```

So, i'm guessing that is probably an old reference to `https://mirror.ehv.weppel.nl`, and I finally found another zip version I could download, `script.xbmcbackup-1.6.7.zip1` here: https://mirrors.kodi.tv/addons/matrix/script.xbmcbackup/

That one installs. So, I try to set up an NFS directory for the backup - first it complained with Error, I guessed it was permissions, gave 777 permissions to folder, adding the path passed. Then I try and do a backup, and it fails with this:

```
2022-02-02 21:31:27.284 T:31617    INFO <general>: Loading skin file: FileBrowser.xml, load type: KEEP_IN_MEMORY
2022-02-02 21:31:39.992 T:31617   ERROR <general>: Unable to lookup host: ''
2022-02-02 21:32:03.083 T:31617 WARNING <general>: FileNFS::OpenForWrite() called with overwriting enabled! - //vid/zip/1
2022-02-02 21:32:03.134 T:31617   ERROR <general>: CNFSFile::Open: Unable to open file : '//vid/zip/1' error : 'open call failed with "NFS: Lookup of /vid/zip/1 failed with NFS3ERR_NOENT(-2)"'
2022-02-02 21:32:12.077 T:31617 WARNING <general>: FileNFS::OpenForWrite() called with overwriting enabled! - //vid/zip/1
2022-02-02 21:32:12.129 T:31617   ERROR <general>: CNFSFile::Open: Unable to open file : '//vid/zip/1' error : 'open call failed with "NFS: Lookup of /vid/zip/1 failed with NFS3ERR_NOENT(-2)"'
2022-02-02 21:32:33.954 T:31617    INFO <general>: Loading skin file: FileBrowser.xml, load type: KEEP_IN_MEMORY
2022-02-02 21:32:41.479 T:31658    INFO <general>: WebSocket: connection closed by client
2022-02-02 21:32:41.480 T:31658    INFO <general>: JSONRPC Server: Disconnection detected
2022-02-02 21:33:26.434 T:31617   ERROR <general>: Unable to lookup host: ''
2022-02-02 21:33:39.242 T:31617 WARNING <general>: FileNFS::OpenForWrite() called with overwriting enabled! - //vid/zip/1
2022-02-02 21:34:55.472 T:1872     INFO <general>: CPythonInvoker(15, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/default.py): script successfully run
2022-02-02 21:34:56.703 T:1872     INFO <general>: Python interpreter stopped
2022-02-02 21:35:00.933 T:1916     INFO <general>: initializing python engine.
2022-02-02 21:35:07.096 T:31617    INFO <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2022-02-02 21:35:14.443 T:31617    INFO <general>: NFS is idle. Closing the remaining connections.
2022-02-02 21:35:15.562 T:1916  WARNING <CSettingInt>: unknown options filler "audiocdactions" of "audiocds.autoaction"
2022-02-02 21:35:15.578 T:1916    ERROR <general>: GetDirectory - Error getting /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/media/Fonts/
2022-02-02 21:35:15.578 T:1916    ERROR <general>: GetDirectory - Error getting special://home/media/Fonts/
2022-02-02 21:36:08.367 T:1916    ERROR <general>: Rename - Error renaming file /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp/xbmc_backup_temp.zip
2022-02-02 21:36:08.653 T:1916    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ZeroDivisionError'>
                                                   Error Contents: float division by zero
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/default.py", line 140, in <module>
                                                       backup.backup()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/resources/lib/backup.py", line 198, in backup
                                                       fileCopied = self._copyFiles(fileManager.getFiles(), self.xbmc_vfs, self.remote_vfs)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/resources/lib/backup.py", line 421, in _copyFiles
                                                       self._updateProgress('%s remaining, writing %s' % (utils.diskString(self.transferLeft), os.path.basename(aFile['file'][len(source.root_path):])))
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.xbmcbackup/resources/lib/backup.py", line 471, in _updateProgress
                                                       self.progressBar.updateProgress(int((float(self.transferSize - self.transferLeft) / float(self.transferSize)) * 100), message)
                                                   ZeroDivisionError: float division by zero
                                                   -->End of Python script error report<--
                                                   
2022-02-02 21:36:09.944 T:1916     INFO <general>: Python interpreter stopped
```

From what I can read `self.transferSize` ended up being zero, and that situation is unhandled.

--------

Edit - tested saving backup on internal SD card, it worked - but then I realized it was folders and directories! So I went to Settings/General/Compress Archives - enabled it, tried Backup again, same error as above.

**Platform and Kodi version**

Kodi 19.1.0 on Android 9.0.0

**Link to Debug Log**

Pasted relevant snippets above

**Comment by robweber** [comment]
Thanks for all the information. As far as the top part goes I imagine you're right and it's some kind of issue with the mirror system. I've had that happen when certain domains or countries are blocked on a connection too. 

As far as the actual error there seem to be a lot of things going on. It looks like the file write operations are working. Probably resulting in a lot of files with either 0 bytes or just no files at all. I imagine that is what lead to the divide by zero error. That particular error definitely shouldn't happen though so I'll iron that out.
