### ISSUE TITLE
Restore fail: Error Contents: 'is_dir' (Ver 1.7)

### ISSUE THREAD

**Issue by sviet2k** [robweber/xbmcbackup#237]
Hi,

I am sorry. This is a duplicated ticket. Please ignore it.
I cannot close or delete this.

Thank you

Hi,

In backup version 1.7, I received following error when trying to restore. (The Backup Option works correctly.)
Please help me to fix this issue when you have time.

Thank you

2024-05-06 19:21:23.952 T:17307   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'is_dir'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/kodi/.kodi/addons/script.xbmcbackup/default.py", line 136, in <module>
                                                       backup.restore()
                                                     File "/storage/emulated/0/kodi/.kodi/addons/script.xbmcbackup/resources/lib/backup.py", line 235, in restore
                                                       self._copyFiles(zipFile, self.remote_vfs, self.xbmc_vfs)
                                                     File "/storage/emulated/0/kodi/.kodi/addons/script.xbmcbackup/resources/lib/backup.py", line 424, in _copyFiles
                                                       if(aFile['is_dir']):
                                                          ~~~~~^^^^^^^^^^
                                                   KeyError: 'is_dir'

**Comment by sviet2k** [comment]
Sorry Duplicated ticket

**Comment by sviet2k** [comment]
Sorry. Duplicated ticket.
