### ISSUE TITLE
Backup error

### ISSUE THREAD

**Issue by demex2008** [robweber/xbmcbackup#238]
Hello, I can't create a backup on my Xbox X with Kodi 21, it always crashes with an error.
[kodi.log](https://github.com/robweber/xbmcbackup/files/15299268/kodi.log)

 Error Type: <class 'RuntimeError'>
 Error Contents: Unknown exception thrown from the call "XBMCAddon::xbmc::executeJSONRPC"
 Traceback (most recent call last):
 File "Q:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\script.xbmcbackup\default.py", line 139, in <module>
 backup.backup()
 File "Q:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\script.xbmcbackup\resources\lib\backup.py", line 156, in backup
 writeCheck = self._createValidationFile(allFiles)
 File "Q:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\script.xbmcbackup\resources\lib\backup.py", line 515, in _createValidationFile
 gui_settings = GuiSettingsManager()
 File "Q:\Users\UserMgr0\AppData\Local\Packages\XBMCFoundation.Kodi_4n2hpmxwrvr6p\LocalState\addons\script.xbmcbackup\resources\lib\guisettings.py", line 12, in __init__
 json_response = json.loads(xbmc.executeJSONRPC('{"jsonrpc":"2.0", "id":1, "method":"Settings.GetSettings","params":{"level":"expert"}}'))
 untimeError: Unknown exception thrown from the call "XBMCAddon::xbmc::executeJSONRPC"
 -->End of Python script error report<--

**Comment by robweber** [comment]
This is a RuntimeError being thrown by the Kodi app. It's being triggered by the JSON-RPC call but it's actually Kodi itself throwing the error. Maybe a bug in the Xbox binaries? I can't fix this, the Kodi devs might be able to reproduce.
