### ISSUE TITLE
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python

### ISSUE THREAD

**Issue by elproducto** [robweber/xbmcbackup#82]
Trying to restore a backup using Backup Addon for Kodi using OpenElec OS.  I get the following error message. Not sure what to do next to troubleshoot.

```

16:04:45` T:140174949750528  NOTICE: script.xbmcbackup-1.0.6: Starting
16:05:57 T:140174949750528  NOTICE: script.xbmcbackup-1.0.6: Local Dir: /storage/.kodi/
16:05:57 T:140174949750528  NOTICE: script.xbmcbackup-1.0.6: Remote Dir: /storage/
16:05:57 T:140174949750528  NOTICE: script.xbmcbackup-1.0.6: Mode - Restore
16:05:57 T:140174949750528  NOTICE: script.xbmcbackup-1.0.6: copying zip file: 201603212241.zip
16:05:57 T:140174949750528  NOTICE: script.xbmcbackup-1.0.6: Writing files to: /storage/.kodi/temp/
16:05:57 T:140174949750528  NOTICE: script.xbmcbackup-1.0.6: Source: /storage/
16:06:48 T:140174949750528  NOTICE: script.xbmcbackup-1.0.6: extracting zip archive
16:07:44 T:140174949750528   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.xbmcbackup/default.py", line 73, in <module>
                                                backup.run(mode)
                                              File "/storage/.kodi/addons/script.xbmcbackup/resources/lib/backup.py", line 319, in run
                                              File "/storage/.kodi/addons/script.xbmcbackup/resources/lib/utils.py", line 24, in `getSetting
[default.py.txt](https://github.com/robweber/xbmcbackup/files/189739/default.py.txt)
[backup.py.txt](https://github.com/robweber/xbmcbackup/files/189740/backup.py.txt)
[utils.py.txt](https://github.com/robweber/xbmcbackup/files/189741/utils.py.txt)


```

**Comment by robweber** [comment]
I think this might be the same as another issue already open. Seems there is a typo on line 319 of the backup.py file.
